### ISSUE TITLE
Add a built-in php server

### ISSUE THREAD

**Issue by reisraff** [reisraff/phulp#21]

**Comment by mik-laj** [comment]
I think that it should not be in the core. External library should better fulfill for that feature.

**Comment by reisraff** [comment]
@mik-laj I agree with you. Have you an idea to do this?

**Comment by mik-laj** [comment]
@reisraff, I am a programmer Javascript. I do not know PHP well, and especially those in multiple threads.
I became interested in this project because it is a competition tool for everyday use. 

But I'll leave a link to another project that can be source of inspiration.
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/ServerRunCommand.php

**Comment by reisraff** [comment]
https://github.com/reisraff/phulp-server
